### ISSUE TITLE
Firefox says one of the links is suspicious

### ISSUE THREAD

**Issue by srinathjayaraman** [geshan/au-companies-providing-work-visa-sponsorship#100]
I clicked on the link for Oliver Wyman Labs and Firefox said it's a potential security risk. Screenshot attached. 

URL is: https://tech.labs.oliverwyman.com/ow-join/join-us/ 

![image](https://user-images.githubusercontent.com/11828799/201487267-202a1034-4821-4c3a-b33e-a469772b0d6d.png)

**Comment by geshan** [comment]
Hello @srinathjayaraman , would you like to open a PR to remove Oliver Wyman Labs?

**Comment by srinathjayaraman** [comment]
Sure, I'll open one and paste the details here.

**Comment by srinathjayaraman** [comment]
[Here is the PR I just opened!](https://github.com/geshan/au-companies-providing-work-visa-sponsorship/pull/102)

**Comment by geshan** [comment]
Thanks!
