### ISSUE TITLE
Is AU Tech Jobs safe site??

### ISSUE THREAD

**Issue by Yoshiki-Iwasa** [geshan/au-companies-providing-work-visa-sponsorship#134]
@geshan 
Thank you for listing au companies that potentially offer visa support.

I'm wondering if [AU Tech Jobs](https://app.autechjobs.com/) is a safe site because there are some strange points on the site.
(ex:
 - It shows two pricing plans but no explanation about the details
 - There is no way to delete my account from autechjobs.
 - The contact form on the site doesn't work(I got 405 error when I sent some questions).
 - the domain owner's information is hidden.

It would be better to add more explanation about autechjobs on the README if you make sure this service is safe.

**Comment by geshan** [comment]
Hello, @Yoshiki-Iwasa it is safe, but you have raised valid concerns, please read through this:  https://geshan.com.np/blog/2021/06/life-changing-side-project/ - on why the project was made.

* We have not implemented any pricing (and probably will not in the near future)
* Send an email to contact if you want to delete your account - contact@autechjobs.com
* I will try to fix the contact form
* It is for security reasons.
