### ISSUE TITLE
Check with redbubble

### ISSUE THREAD

**Issue by sreeram-boyapati** [geshan/au-companies-providing-work-visa-sponsorship#93]
RedBubble clearly mentioned they do not sponsor visa in their LinkedIn job post. We need to check with their team again if they sponsor visa. The role does not seem like an entry-level role, most probably mid-senior.

https://www.linkedin.com/jobs/view/2440608077

**Comment by geshan** [comment]
Please open a PR to remove redbubble, @sreeram-boyapati thanks!
